[net]
tickrate = 30

[netres]
limit = 25.0

[infolinks]
discord = "https://discord.gg/cy6eKZME8H"
github = "https://github.com/corvax-team/ss14-wl"
wiki = "https://station14.ru/wiki/Портал:WhiteList"
patreon = "https://boosty.to/corvaxwl"
appeal = "https://discord.ss14.ru"
bug_report = "https://github.com/corvax-team/ss14-wl/issues/new/choose"
website = "https://ss14.ru"

[viewport]
maximum_width = 26

[game]
lobbyduration = 360
map_pool = "WhitelistMapPool"
secret_weight_prototype = "CorvaxSecretDefault"
round_restart_time = 240

[server]
rules_file = "CorvaxRuleset"

[discord]
rich_main_icon_id = "corvax"

[admin]
see_own_notes = true
