[game]
hostname = "üõ∞Ô∏è Corvax ‚Äî –í–∞–π—Ç–ª–∏—Å—Ç ‚òï[TTS]"
desc = "–†—É—Å—Å–∫–æ—è–∑—ã—á–Ω—ã–π —Å–µ—Ä–≤–µ—Ä –ø—Ä–æ–µ–∫—Ç–∞ Corvax —Å –ø–æ–≤—ã—à–µ–Ω–Ω—ã–º —É—Ä–æ–≤–Ω–µ–º –†–ü –∏ –¥–æ—Å—Ç—É–ø–æ–º –ø–æ –≤–∞–π—Ç–ª–∏—Å—Ç—É.\n–î–ª—è –ø–æ–ª—É—á–µ–Ω–∏—è –¥–æ—Å—Ç—É–ø–∞ –æ–±—Ä–∞—Ç–∏—Ç–µ—Å—å –≤ –Ω–∞—à Discord!"
maxplayers = 80
soft_max_players = 70
map_rotation = true
role_timers = false
peaceful_end = false
cryo_sleep_rejoining = true
secret_weight_prototype = "Secret"

[server]
lobby_name = "Ô∏èüõ∞Ô∏è Corvax ‚Äî –í–∞–π—Ç–ª–∏—Å—Ç ‚òï"
rules_file = "CorvaxWLRuleset"

[atmos]
space_wind = true

[biomass]
easy_mode = false

[rules]
time = 10.0

[whitelist]
enabled = true

[ic]
flavor_text = true
flavor_text_length = 1536
punctuation = true

[salvage]
expedition_duration = 900.0

[shuttle]
auto_call_time = 0

[hub]
advertise = true
tags = "lang:ru,rp:high,region:eu_e,tts"

[worldgen]
enabled = true
