- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  startingGear: CargoTechGear
  subnames:
  - Male: работник склада
  - Male: курьер
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  requirements:
    - !type:AgeRequirement
      minAge: 18

- type: startingGear
  id: CargoTechGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff
