- type: weightedRandom
  id: StationGoalRandomDiscipline
  weights:
    research-discipline-industrial: 1
    research-discipline-arsenal: 1
    research-discipline-experimental: 1
    research-discipline-civilian-services: 1

- type: weightedRandom
  id: StationGoalRandomIntegerBetweenFiveteenAndThirdteen
  weights:
    15: 1
    16: 1
    17: 1
    18: 1
    19: 1
    20: 1
    21: 1
    22: 1
    23: 1
    24: 1
    25: 1
    26: 1
    27: 1
    28: 1
    29: 1
    30: 1

- type: weightedRandom
  id: StationGoalRandomReagent
  weights:
    некрозола: 1
    дифенилметиламина: 1
    психодина: 1

# Мне лень добавлять ftl-ки, всё равно эти строки используются только на вле
- type: weightedRandom
  id: StationGoalRandomMedicalKitsPair
  weights:
    "механических и физических повреждений": 1
    "механических повреждений и токсинов": 1
    "механических повреждений и радиации": 1
    "механических повреждений и кислородного голодания": 1
    "физических повреждений и токсинов": 1
    "физических повреждений и радиации": 1
    "физических повреждений и кислородного голодания": 1
    "токсинов и радиации": 1
    "токсинов и кислородного голодания": 1
    "радиации и кислородного голодания": 1

- type: weightedRandom
  id: StationGoalRandomFrezonDestination
  weights:
    "склад научного отдела для дальнейших исследований": 1
    "автоматическую торговую станцию": 1

- type: weightedRandom
  id: StationGoalRandomOre
  weights:
    ураном: 1
    "железной рудой": 1
    "космическим кварцем": 1
    #золотом: 1
    #бананиумом: 1

- type: weightedRandom
  id: StationGoalRandomArtifactVerb
  weights:
    добыча: 1
    покупка: 1

- type: weightedRandom
  id: StationGoalRandomServiceCrate
  weights:
    "божественной амброзии": 1
    "кровяных томатов": 1
    "синих томатов": 1
    "брёвен сталешляпника": 1
    пирохлопка: 1
    смертокрапивы: 1
    лимунов: 1
    смехогороха: 1
    "морозного чилли": 1