- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  subnames:
  - Male: ассистент
  - Male: художник
  - Male: юрист
  - Male: фрилансер
  - Male: экипаж вне службы
  - Male: турист
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
#  access: # Corvax-MRP
#  - Maintenance

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff
