- type: ertConfig
  id: Standart
  entry:
    # Clowns:
      # shuttlePath: /Maps/Shuttles/dart.ym
      # spawnPoint: RandomHumanoidSpawnerERTChaplain
    Engineers:
      shuttlePath: /Maps/_WL/Shuttles/dart.yml
      spawnPoint: RandomHumanoidSpawnerERTEngineer
    Security:
      shuttlePath: /Maps/_WL/Shuttles/dart.yml
      spawnPoint: RandomHumanoidSpawnerERTSecurity
    Medical:
      shuttlePath: /Maps/_WL/Shuttles/dart.yml
      spawnPoint: RandomHumanoidSpawnerERTMedical
    Janitors:
      shuttlePath: /Maps/_WL/Shuttles/dart.yml
      spawnPoint: RandomHumanoidSpawnerERTJanitor
    Chaplains:
      shuttlePath: /Maps/_WL/Shuttles/dart.yml
      spawnPoint: RandomHumanoidSpawnerERTChaplain